<<<<<<< HEAD
pg_database: "your_pg_database"
pg_username: "your_pg_username"
pg_password: "your_pg_password"
google_client_id: "your_google_client_id"
google_client_secret: "your_google_client_secret"
hash_key: "flycat_hash_key"
hash_iv: "flycat_hash_iv"
merchant_id: "flycat_merchant_id"
return_url: "your_ngrok_return_url"
notify_url: "notify_url"
=======
PG_DATABASE: "YOUR_PG_DATABASE"
PG_USERNAME: "YOUR_PG_USERNAME"
PG_PASSWORD: "YOUR_PG_PASSWORD"
Github_Client_ID: "YOUR_Github_Client_ID"
Github_Client_Secret: "YOUR_Github_Client_Secret"
google_client_id: "YOUR_google_client_id"
google_client_secret: "YOUR_google_client_secret"
hash_key: "Flycat_hash_key"
hash_iv: "Flycat_hash_iv"
merchant_id: "Flycat_merchant_id"
your_ngrok: "your_ngrok"
return_url: "https://Your_ngrok"
notify_url: "NotifyURL"
your_email: "your_email"
your_email_password: "your_password"
>>>>>>> 26236a1 (docs(錯誤訊ｐ息): 員工資訊)
